using ProtoBuf;
using System.Collections.Generic;
using System.ComponentModel;

namespace CodeiumVS.Packets;
// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   https://protogen.marcgravell.com/
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192, IDE0028
[global::ProtoBuf.ProtoContract()]
public partial class GetCompletionsRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public Metadata metadata { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public Document document {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public EditorOptions editor_options {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    public global::System.Collections.Generic.List<Document> other_documents {
        get;
    } = new global::System.Collections.Generic.List<Document>();

    [global::ProtoBuf.ProtoMember(6)]
    public MockResponseData mock_response_data {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(8)]
    public bool disable_cache {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(9)]
    public global::System.Collections.Generic.List<CodeContextItem> oracle_items {
        get;
    } = new global::System.Collections.Generic.List<CodeContextItem>();

    [global::ProtoBuf.ProtoMember(10)]
    [global::System.ComponentModel.DefaultValue("")]
    public string model_name {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class Metadata : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ide_name { get; set; } = "";

    [global::ProtoBuf.ProtoMember(7)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ide_version {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(12)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extension_name {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extension_version {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string api_key {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string locale {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue("")]
    public string os {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(8)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hardware {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(6)]
    public bool disable_telemetry {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(10)]
    [global::System.ComponentModel.DefaultValue("")]
    public string session_id {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(16)]
    [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
    public global::System.DateTime? ls_timestamp {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(9)]
    public ulong request_id {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(11)]
    [global::System.ComponentModel.DefaultValue("")]
    public string source_address {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(13)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_agent {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(14)]
    [global::System.ComponentModel.DefaultValue("")]
    public string url {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(17)]
    [global::System.ComponentModel.DefaultValue("")]
    public string extension_path {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(19)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip_address {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(20)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_id {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class Document : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string absolute_path { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string relative_path {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string editor_language {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(5)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(6)]
    public ulong cursor_offset {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(8)]
    public DocumentPosition cursor_position {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(7)]
    [global::System.ComponentModel.DefaultValue("")]
    public string line_ending {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(9)]
    public Range visible_range {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class DocumentPosition : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ulong row { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public ulong col {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class Range : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ulong startOffset { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public ulong endOffset {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public DocumentPosition startPosition {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    public DocumentPosition endPosition {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class EditorOptions : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ulong tab_size { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public bool insert_spaces {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public bool disable_autocomplete_in_comments {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class MockResponseData : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public global::System.Collections.Generic.List<Completion> completions {
        get;
    } = new global::System.Collections.Generic.List<Completion>();
}

[global::ProtoBuf.ProtoContract()]
public partial class Completion : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string completionId { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stop {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(5)]
    public double score {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(6, IsPacked = true)]
    public ulong[] tokens {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(7)]
    public global::System.Collections.Generic.List<string> decodedTokens {
        get;
    } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(8, IsPacked = true)]
    public double[] probabilities {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(9, IsPacked = true)]
    public double[] adjustedProbabilities {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(10)]
    public ulong generatedLength {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(12)]
    public StopReason stopReason {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(13, IsPacked = true)]
    public global::System.Collections.Generic.List<FilterReason> filterReasons {
        get;
    } = new global::System.Collections.Generic.List<FilterReason>();

    [global::ProtoBuf.ProtoMember(14)]
    [global::System.ComponentModel.DefaultValue("")]
    public string originalText {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Obsolete]
    public string prefix {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(11)]
    [global::System.Obsolete]
    public double entropy {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class CodeContextItem : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string absolute_path { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public global::System.Collections.Generic.List<WorkspacePath> workspace_paths {
        get;
    } = new global::System.Collections.Generic.List<WorkspacePath>();

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string node_name {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    public global::System.Collections.Generic.List<string> node_lineage {
        get;
    } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(5)]
    public uint start_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(12)]
    public uint start_col {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(6)]
    public uint end_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(13)]
    public uint end_col {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(7)]
    public CodeContextType context_type {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(10)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(11)]
    [global::ProtoBuf.ProtoMap]
    public global::System.Collections.Generic
        .Dictionary<string, SnippetWithWordCount> snippet_by_type {
            get;
        } = new global::System.Collections.Generic.Dictionary<string, SnippetWithWordCount>();

    [global::ProtoBuf.ProtoMember(14)]
    public GitRepoInfo repo_info {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(15)]
    public byte[] file_content_hash {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class WorkspacePath : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string workspace { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string relative_path {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class SnippetWithWordCount : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string snippet { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::ProtoBuf.ProtoMap]
    public global::System.Collections.Generic.Dictionary<string, WordCount> word_count_by_splitter {
        get;
    } = new global::System.Collections.Generic.Dictionary<string, WordCount>();
}

[global::ProtoBuf.ProtoContract()]
public partial class WordCount : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::ProtoBuf.ProtoMap]
    public global::System.Collections.Generic.Dictionary<string, long> word_count_map {
        get;
    } = new global::System.Collections.Generic.Dictionary<string, long>();
}

[global::ProtoBuf.ProtoContract()]
public partial class GitRepoInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string owner {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue("")]
    public string repo_name {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string commit {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version_alias {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class GetCompletionsResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public State state { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public global::System.Collections.Generic.List<CompletionItem> completionItems {
        get;
    } = new global::System.Collections.Generic.List<CompletionItem>();

    [global::ProtoBuf.ProtoMember(7)]
    public global::System.Collections.Generic.List<CompletionItem> filteredCompletionItems {
        get;
    } = new global::System.Collections.Generic.List<CompletionItem>();

    [global::ProtoBuf.ProtoMember(3)]
    public RequestInfo requestInfo {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    public LatencyInfo latencyInfo {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue("")]
    public string modelTag {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(6)]
    [global::System.ComponentModel.DefaultValue("")]
    public string promptId {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class State : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public CodeiumState state { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class CompletionItem : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public Completion completion { get; set; }

    [global::ProtoBuf.ProtoMember(5)]
    public Suffix suffix {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(2)]
    public Range range {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public CompletionSource source {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(8)]
    public global::System.Collections.Generic.List<CompletionPart> completionParts {
        get;
    } = new global::System.Collections.Generic.List<CompletionPart>();
}

[global::ProtoBuf.ProtoContract()]
public partial class Suffix : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public long delta_cursor_offset {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class CompletionPart : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public ulong offset {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public CompletionPartType type {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prefix {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(5)]
    public ulong line {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class RequestInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prompt_id { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3)]
    public LineType line_type {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    public CompletionsRequest completions_request {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue("")]
    public string typing_as_suggested_prompt_suffix {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class CompletionsRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public CompletionConfiguration configuration { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prompt {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(8)]
    public global::System.Collections.Generic.List<PromptElementRange> prompt_element_ranges {
        get;
    } = new global::System.Collections.Generic.List<PromptElementRange>();

    [global::ProtoBuf.ProtoMember(9)]
    public global::System.Collections.Generic
        .List<PromptElementKindInfo> prompt_element_kind_infos {
            get;
        } = new global::System.Collections.Generic.List<PromptElementKindInfo>();

    [global::ProtoBuf.ProtoMember(11)]
    public ulong prompt_latency_ms {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(12)]
    public global::System.Collections.Generic.List<PromptStageLatency> prompt_stage_latencies {
        get;
    } = new global::System.Collections.Generic.List<PromptStageLatency>();

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string editor_language {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue("")]
    public string absolute_path {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(6)]
    [global::System.ComponentModel.DefaultValue("")]
    public string relative_path {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(13)]
    [global::System.ComponentModel.DefaultValue("")]
    public string workspace {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(7)]
    [global::System.ComponentModel.DefaultValue("")]
    public string experiment_features_json {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(14)]
    public bool has_line_suffix {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(15)]
    public bool should_inline_fim {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(16)]
    public Repository repository {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(17)]
    [global::System.ComponentModel.DefaultValue("")]
    public string model_tag {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(18)]
    public global::System.Collections.Generic.List<string> experiment_tags {
        get;
    } = new global::System.Collections.Generic.List<string>();
}

[global::ProtoBuf.ProtoContract()]
public partial class CompletionConfiguration : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ulong num_completions { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public ulong max_tokens {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public ulong max_newlines {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    public double min_log_probability {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    public double temperature {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(6)]
    public double first_temperature {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(7)]
    public ulong top_k {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(8)]
    public double top_p {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(9)]
    public global::System.Collections.Generic.List<string> stop_patterns {
        get;
    } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(10)]
    public ulong seed {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(11)]
    public double fim_eot_prob_threshold {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(12)]
    public bool use_fim_eot_threshold {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(13)]
    public bool do_not_score_stop_tokens {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(14)]
    public bool sqrt_len_normalized_log_prob_score {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class PromptElementRange : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public PromptElementKind kind { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public ulong byte_offset_start {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public ulong byte_offset_end {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    public ulong token_offset_start {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    public ulong token_offset_end {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class PromptElementKindInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public PromptElementKind kind { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public bool enabled {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    public ulong num_considered {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    public ulong num_included {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class PromptStageLatency : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public ulong latency_ms {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class Repository : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string computed_name { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string git_origin_url {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string git_upstream_url {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reported_name {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue("")]
    public string model_name {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(6)]
    [global::System.ComponentModel.DefaultValue("")]
    public string submodule_url {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(7)]
    [global::System.ComponentModel.DefaultValue("")]
    public string submodule_path {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class LatencyInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ulong client_latency_ms { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public ulong prompt_latency_ms {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public global::System.Collections.Generic.List<PromptStageLatency> prompt_stage_latencies {
        get;
    } = new global::System.Collections.Generic.List<PromptStageLatency>();

    [global::ProtoBuf.ProtoMember(4)]
    public ulong debounce_latency_ms {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    public ulong rpc_latency_ms {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(6)]
    public ulong network_latency_ms {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class GetProcessesResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public uint lspPort { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public uint chatWebServerPort {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public uint chatClientPort {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class WebServerRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public HandshakeRequest handshake_request
    {
        get => __pbn__payload.Is(1) ? ((HandshakeRequest)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializehandshake_request() => __pbn__payload.Is(1);
    public void Resethandshake_request() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__payload;

    [global::ProtoBuf.ProtoMember(2)]
    public GetChatMessageRequest get_chat_message_request
    {
        get => __pbn__payload.Is(2) ? ((GetChatMessageRequest)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeget_chat_message_request() => __pbn__payload.Is(2);
    public void Resetget_chat_message_request() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 2);

    [global::ProtoBuf.ProtoMember(3)]
    public RecordChatFeedbackRequest record_chat_feedback_request
    {
        get => __pbn__payload.Is(3) ? ((RecordChatFeedbackRequest)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
    }
    public bool ShouldSerializerecord_chat_feedback_request() => __pbn__payload.Is(3);
    public void Resetrecord_chat_feedback_request() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 3);

    [global::ProtoBuf.ProtoMember(4)]
    public ClearConversation clear_conversation
    {
        get => __pbn__payload.Is(4) ? ((ClearConversation)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
    }
    public bool ShouldSerializeclear_conversation() => __pbn__payload.Is(4);
    public void Resetclear_conversation() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 4);

    [global::ProtoBuf.ProtoMember(5)]
    public OpenFilePointer open_file_pointer
    {
        get => __pbn__payload.Is(5) ? ((OpenFilePointer)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
    }
    public bool ShouldSerializeopen_file_pointer() => __pbn__payload.Is(5);
    public void Resetopen_file_pointer() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 5);

    [global::ProtoBuf.ProtoMember(6)]
    public CancelInfightMessage cancel_infight_message
    {
        get => __pbn__payload.Is(6) ? ((CancelInfightMessage)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
    }
    public bool ShouldSerializecancel_infight_message() => __pbn__payload.Is(6);
    public void Resetcancel_infight_message() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 6);

    [global::ProtoBuf.ProtoMember(7)]
    public InsertCodeAtCursor insert_at_cursor
    {
        get => __pbn__payload.Is(7) ? ((InsertCodeAtCursor)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
    }
    public bool ShouldSerializeinsert_at_cursor() => __pbn__payload.Is(7);
    public void Resetinsert_at_cursor() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 7);

    [global::ProtoBuf.ProtoMember(8)]
    public ApplyDiff apply_diff
    {
        get => __pbn__payload.Is(8) ? ((ApplyDiff)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
    }
    public bool ShouldSerializeapply_diff() => __pbn__payload.Is(8);
    public void
    Resetapply_diff() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 8);

    [global::ProtoBuf.ProtoMember(9)]
    public Heartbeat heartbeat
    {
        get => __pbn__payload.Is(9) ? ((Heartbeat)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(9, value);
    }
    public bool ShouldSerializeheartbeat() => __pbn__payload.Is(9);
    public void
    Resetheartbeat() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 9);

    [global::ProtoBuf.ProtoMember(10)]
    public UpdateUserSettingsRequest update_user_settings
    {
        get => __pbn__payload.Is(10) ? ((UpdateUserSettingsRequest)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(10, value);
    }
    public bool ShouldSerializeupdate_user_settings() => __pbn__payload.Is(10);
    public void Resetupdate_user_settings() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 10);
}

[global::ProtoBuf.ProtoContract()]
public partial class HandshakeRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public Metadata metadata { get; set; }

    [global::ProtoBuf.ProtoMember(9)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_id {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class GetChatMessageRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public Metadata metadata { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prompt {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(3)]
    public global::System.Collections.Generic.List<ChatMessage> chat_messages {
        get;
    } = new global::System.Collections.Generic.List<ChatMessage>();

    [global::ProtoBuf.ProtoMember(5)]
    public Document active_document {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(6)]
    public global::System.Collections.Generic.List<string> open_document_paths {
        get;
    } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(7)]
    public global::System.Collections.Generic.List<string> workspace_paths {
        get;
    } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(8)]
    public ContextInclusionType context_inclusion_type {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class ChatMessage : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message_id { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public ChatMessageSource source {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
    public global::System.DateTime? timestamp {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string conversation_id {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(9)]
    public bool in_progress {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    public ChatMessageIntent intent
    {
        get => __pbn__content.Is(5) ? ((ChatMessageIntent)__pbn__content.Object) : default;
        set => __pbn__content = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
    }
    public bool ShouldSerializeintent() => __pbn__content.Is(5);
    public void Resetintent() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__content,
                                                                                 5);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__content;

    [global::ProtoBuf.ProtoMember(6)]
    public ChatMessageAction action
    {
        get => __pbn__content.Is(6) ? ((ChatMessageAction)__pbn__content.Object) : default;
        set => __pbn__content = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
    }
    public bool ShouldSerializeaction() => __pbn__content.Is(6);
    public void Resetaction() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__content,
                                                                                 6);

    [global::ProtoBuf.ProtoMember(7)]
    public ChatMessageError error
    {
        get => __pbn__content.Is(7) ? ((ChatMessageError)__pbn__content.Object) : default;
        set => __pbn__content = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
    }
    public bool ShouldSerializeerror() => __pbn__content.Is(7);
    public void Reseterror() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__content,
                                                                                7);

    [global::ProtoBuf.ProtoMember(8)]
    public ChatMessageStatus status
    {
        get => __pbn__content.Is(8) ? ((ChatMessageStatus)__pbn__content.Object) : default;
        set => __pbn__content = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
    }
    public bool ShouldSerializestatus() => __pbn__content.Is(8);
    public void Resetstatus() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__content,
                                                                                 8);
}

[global::ProtoBuf.ProtoContract()]
public partial class ChatMessageIntent : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public IntentGeneric generic
    {
        get => __pbn__intent.Is(1) ? ((IntentGeneric)__pbn__intent.Object) : default;
        set => __pbn__intent = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializegeneric() => __pbn__intent.Is(1);
    public void Resetgeneric() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__intent,
                                                                                  1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__intent;

    [global::ProtoBuf.ProtoMember(2)]
    public IntentFunctionExplain explain_function
    {
        get => __pbn__intent.Is(2) ? ((IntentFunctionExplain)__pbn__intent.Object) : default;
        set => __pbn__intent = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeexplain_function() => __pbn__intent.Is(2);
    public void Resetexplain_function() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__intent, 2);

    [global::ProtoBuf.ProtoMember(3)]
    public IntentFunctionDocstring function_docstring
    {
        get => __pbn__intent.Is(3) ? ((IntentFunctionDocstring)__pbn__intent.Object) : default;
        set => __pbn__intent = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
    }
    public bool ShouldSerializefunction_docstring() => __pbn__intent.Is(3);
    public void Resetfunction_docstring() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__intent, 3);

    [global::ProtoBuf.ProtoMember(4)]
    public IntentFunctionRefactor function_refactor
    {
        get => __pbn__intent.Is(4) ? ((IntentFunctionRefactor)__pbn__intent.Object) : default;
        set => __pbn__intent = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
    }
    public bool ShouldSerializefunction_refactor() => __pbn__intent.Is(4);
    public void Resetfunction_refactor() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__intent, 4);

    [global::ProtoBuf.ProtoMember(5)]
    public IntentCodeBlockExplain explain_code_block
    {
        get => __pbn__intent.Is(5) ? ((IntentCodeBlockExplain)__pbn__intent.Object) : default;
        set => __pbn__intent = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
    }
    public bool ShouldSerializeexplain_code_block() => __pbn__intent.Is(5);
    public void Resetexplain_code_block() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__intent, 5);

    [global::ProtoBuf.ProtoMember(6)]
    public IntentCodeBlockRefactor code_block_refactor
    {
        get => __pbn__intent.Is(6) ? ((IntentCodeBlockRefactor)__pbn__intent.Object) : default;
        set => __pbn__intent = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
    }
    public bool ShouldSerializecode_block_refactor() => __pbn__intent.Is(6);
    public void Resetcode_block_refactor() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__intent, 6);

    [global::ProtoBuf.ProtoMember(7)]
    public IntentFunctionUnitTests function_unit_tests
    {
        get => __pbn__intent.Is(7) ? ((IntentFunctionUnitTests)__pbn__intent.Object) : default;
        set => __pbn__intent = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
    }
    public bool ShouldSerializefunction_unit_tests() => __pbn__intent.Is(7);
    public void Resetfunction_unit_tests() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__intent, 7);

    [global::ProtoBuf.ProtoMember(8)]
    public IntentProblemExplain problem_explain
    {
        get => __pbn__intent.Is(8) ? ((IntentProblemExplain)__pbn__intent.Object) : default;
        set => __pbn__intent = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
    }
    public bool ShouldSerializeproblem_explain() => __pbn__intent.Is(8);
    public void
    Resetproblem_explain() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__intent, 8);

    [global::ProtoBuf.ProtoMember(9)]
    public IntentGenerateCode generate_code
    {
        get => __pbn__intent.Is(9) ? ((IntentGenerateCode)__pbn__intent.Object) : default;
        set => __pbn__intent = new global::ProtoBuf.DiscriminatedUnionObject(9, value);
    }
    public bool ShouldSerializegenerate_code() => __pbn__intent.Is(9);
    public void
    Resetgenerate_code() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__intent, 9);

    [global::ProtoBuf.ProtoMember(10)]
    public IntentClassExplain explain_class
    {
        get => __pbn__intent.Is(10) ? ((IntentClassExplain)__pbn__intent.Object) : default;
        set => __pbn__intent = new global::ProtoBuf.DiscriminatedUnionObject(10, value);
    }
    public bool ShouldSerializeexplain_class() => __pbn__intent.Is(10);
    public void
    Resetexplain_class() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__intent, 10);
}

[global::ProtoBuf.ProtoContract()]
public partial class IntentGeneric : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text { get; set; } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class IntentFunctionExplain : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public FunctionInfo function_info { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class FunctionInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string raw_source { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clean_function {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string docstring {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string node_name {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue("")]
    public string @params {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(6)]
    public int definition_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(7)]
    public int start_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(8)]
    public int end_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(9)]
    public int start_col {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(10)]
    public int end_col {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(11)]
    [global::System.ComponentModel.DefaultValue("")]
    public string leading_whitespace {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(12)]
    public Language language {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class IntentFunctionDocstring : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public FunctionInfo function_info { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class IntentFunctionRefactor : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public FunctionInfo function_info { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string refactor_description {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class IntentCodeBlockExplain : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public CodeBlockInfo code_block_info { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class CodeBlockInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string raw_source { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public int start_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public int start_col {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    public int end_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    public int end_col {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class IntentCodeBlockRefactor : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public CodeBlockInfo code_block_info { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string refactor_description {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class IntentFunctionUnitTests : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public FunctionInfo function_info { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string instructions {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class IntentProblemExplain : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string diagnostic_message { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public CodeBlockInfo problematic_code {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string surrounding_code_snippet {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(6)]
    public int line_number {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class IntentGenerateCode : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string instruction { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    public int line_number {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class IntentClassExplain : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ClassInfo class_info { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class ClassInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string raw_source { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public int start_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public int end_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    public int start_col {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    public int end_col {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(6)]
    [global::System.ComponentModel.DefaultValue("")]
    public string leading_whitespace {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(7)]
    public global::System.Collections.Generic.List<string> fields_and_constructors {
        get;
    } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(8)]
    [global::System.ComponentModel.DefaultValue("")]
    public string docstring {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(9)]
    [global::System.ComponentModel.DefaultValue("")]
    public string node_name {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(10)]
    public global::System.Collections.Generic.List<FunctionInfo> methods {
        get;
    } = new global::System.Collections.Generic.List<FunctionInfo>();

    [global::ProtoBuf.ProtoMember(11)]
    public global::System.Collections.Generic.List<string> node_lineage {
        get;
    } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(12)]
    public bool is_exported {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(13)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(14)]
    public int definition_line {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class ChatMessageAction : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(2)]
    public uint num_tokens { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public global::System.Collections.Generic.List<CodeContextItem> context_items {
        get;
    } = new global::System.Collections.Generic.List<CodeContextItem>();

    [global::ProtoBuf.ProtoMember(1)]
    public ChatMessageActionGeneric generic
    {
        get => __pbn__action.Is(1) ? ((ChatMessageActionGeneric)__pbn__action.Object) : default;
        set => __pbn__action = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializegeneric() => __pbn__action.Is(1);
    public void Resetgeneric() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__action,
                                                                                  1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__action;

    [global::ProtoBuf.ProtoMember(3)]
    public ChatMessageActionEdit edit
    {
        get => __pbn__action.Is(3) ? ((ChatMessageActionEdit)__pbn__action.Object) : default;
        set => __pbn__action = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
    }
    public bool ShouldSerializeedit() => __pbn__action.Is(3);
    public void Resetedit() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__action,
                                                                               3);
}

[global::ProtoBuf.ProtoContract()]
public partial class ChatMessageActionGeneric : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text { get; set; } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class ChatMessageActionEdit : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public DiffBlock diff {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public Language language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text_pre {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text_post {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class DiffBlock : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public int start_line { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public int end_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public UnifiedDiff unified_diff {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    public Language from_language {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    public Language to_language {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class UnifiedDiff : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(3)]
    public global::System.Collections.Generic.List<UnifiedDiffLine> lines {
        get;
    } = new global::System.Collections.Generic.List<UnifiedDiffLine>();

    [global::ProtoBuf.ProtoContract()]
    public partial class UnifiedDiffLine : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension
            global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
            global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData,
                                                           createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string text { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public UnifiedDiffLineType type {
            get; set;
        }
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class ChatMessageError : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text { get; set; } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class ChatMessageStatus : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ChatMessageStatusContextRelevancy context_relevancy { get; set; }
}

[global::ProtoBuf.ProtoContract()]
public partial class ChatMessageStatusContextRelevancy : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public bool is_loading { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public bool is_relevant {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public global::System.Collections.Generic.List<string> query_suggestions {
        get;
    } = new global::System.Collections.Generic.List<string>();
}

[global::ProtoBuf.ProtoContract()]
public partial class RecordChatFeedbackRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public Metadata metadata { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message_id {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(3)]
    public ChatFeedbackType feedback {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(5)]
    [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
    public global::System.DateTime? timestamp {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class ClearConversation : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string conversation_id { get; set; } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class OpenFilePointer : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public int start_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public int start_col {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(4)]
    public int end_line {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    public int end_col {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class CancelInfightMessage : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stream_id { get; set; } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class InsertCodeAtCursor : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    public ActiveEditorType editor_type {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class ApplyDiff : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message_id { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_path {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(3)]
    public DiffBlock diff {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class Heartbeat : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
}

[global::ProtoBuf.ProtoContract()]
public partial class UpdateUserSettingsRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public UserSettings user_settings { get; set; }
}

[global::ProtoBuf.ProtoContract()]
public partial class UserSettings : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public bool open_most_recent_chat_conversation { get; set; }
}

[global::ProtoBuf.ProtoContract()]
public partial class WebServerResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public HandshakeResponse handshake_response
    {
        get => __pbn__payload.Is(1) ? ((HandshakeResponse)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializehandshake_response() => __pbn__payload.Is(1);
    public void Resethandshake_response() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__payload;

    [global::ProtoBuf.ProtoMember(2)]
    public StateUpdate state_update
    {
        get => __pbn__payload.Is(2) ? ((StateUpdate)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializestate_update() => __pbn__payload.Is(2);
    public void
    Resetstate_update() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 2);

    [global::ProtoBuf.ProtoMember(3)]
    public OpenFilePointer open_file_pointer
    {
        get => __pbn__payload.Is(3) ? ((OpenFilePointer)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
    }
    public bool ShouldSerializeopen_file_pointer() => __pbn__payload.Is(3);
    public void Resetopen_file_pointer() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 3);

    [global::ProtoBuf.ProtoMember(4)]
    public InsertCodeAtCursor insert_at_cursor
    {
        get => __pbn__payload.Is(4) ? ((InsertCodeAtCursor)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
    }
    public bool ShouldSerializeinsert_at_cursor() => __pbn__payload.Is(4);
    public void Resetinsert_at_cursor() =>
        global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 4);

    [global::ProtoBuf.ProtoMember(5)]
    public ApplyDiff apply_diff
    {
        get => __pbn__payload.Is(5) ? ((ApplyDiff)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
    }
    public bool ShouldSerializeapply_diff() => __pbn__payload.Is(5);
    public void
    Resetapply_diff() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 5);

    [global::ProtoBuf.ProtoMember(6)]
    public ErrorResponse error_response
    {
        get => __pbn__payload.Is(6) ? ((ErrorResponse)__pbn__payload.Object) : default;
        set => __pbn__payload = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
    }
    public bool ShouldSerializeerror_response() => __pbn__payload.Is(6);
    public void
    Reseterror_response() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__payload, 6);
}

[global::ProtoBuf.ProtoContract()]
public partial class HandshakeResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public UserStatus user_status { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public ChatMessageState initial_state {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string language_server_address {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class UserStatus : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public bool pro { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public bool disable_telemetry {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(4)]
    public bool ignore_chat_telemetry_setting {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue("")]
    public string team_id {
        get; set;
    } = "";

    [global::ProtoBuf.ProtoMember(6)]
    public UserTeamStatus team_status {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class ChatMessageState : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public global::System.Collections.Generic.List<ChatMessageWithFeedback> messages {
        get;
    } = new global::System.Collections.Generic.List<ChatMessageWithFeedback>();

    [global::ProtoBuf.ProtoMember(2)]
    public bool is_receiving_message {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    public UserSettings user_settings {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class ChatMessageWithFeedback : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ChatMessage message { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public ChatFeedbackType feedback {
        get; set;
    }

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stream_id {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class StateUpdate : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public ChatMessageState state { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public bool is_partial_update {
        get; set;
    }
}

[global::ProtoBuf.ProtoContract()]
public partial class ErrorResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string error { get; set; } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class GetAuthTokenRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
}

[global::ProtoBuf.ProtoContract()]
public partial class GetAuthTokenResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string authToken { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uuid {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class RegisterUserRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string firebase_id_token { get; set; } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class RegisterUserResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string api_key { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class AcceptCompletionRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public Metadata metadata { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string completion_id {
        get; set;
    } = "";
}

[global::ProtoBuf.ProtoContract()]
public partial class AcceptCompletionResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension
        global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing) =>
        global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
}

[global::ProtoBuf.ProtoContract()]
public enum Language
{
    LANGUAGE_UNSPECIFIED = 0,
    LANGUAGE_C = 1,
    LANGUAGE_CLOJURE = 2,
    LANGUAGE_COFFEESCRIPT = 3,
    LANGUAGE_CPP = 4,
    LANGUAGE_CSHARP = 5,
    LANGUAGE_CSS = 6,
    LANGUAGE_CUDACPP = 7,
    LANGUAGE_DOCKERFILE = 8,
    LANGUAGE_GO = 9,
    LANGUAGE_GROOVY = 10,
    LANGUAGE_HANDLEBARS = 11,
    LANGUAGE_HASKELL = 12,
    LANGUAGE_HCL = 13,
    LANGUAGE_HTML = 14,
    LANGUAGE_INI = 15,
    LANGUAGE_JAVA = 16,
    LANGUAGE_JAVASCRIPT = 17,
    LANGUAGE_JSON = 18,
    LANGUAGE_JULIA = 19,
    LANGUAGE_KOTLIN = 20,
    LANGUAGE_LATEX = 21,
    LANGUAGE_LESS = 22,
    LANGUAGE_LUA = 23,
    LANGUAGE_MAKEFILE = 24,
    LANGUAGE_MARKDOWN = 25,
    LANGUAGE_OBJECTIVEC = 26,
    LANGUAGE_OBJECTIVECPP = 27,
    LANGUAGE_PERL = 28,
    LANGUAGE_PHP = 29,
    LANGUAGE_PLAINTEXT = 30,
    LANGUAGE_PROTOBUF = 31,
    LANGUAGE_PBTXT = 32,
    LANGUAGE_PYTHON = 33,
    LANGUAGE_R = 34,
    LANGUAGE_RUBY = 35,
    LANGUAGE_RUST = 36,
    LANGUAGE_SASS = 37,
    LANGUAGE_SCALA = 38,
    LANGUAGE_SCSS = 39,
    LANGUAGE_SHELL = 40,
    LANGUAGE_SQL = 41,
    LANGUAGE_STARLARK = 42,
    LANGUAGE_SWIFT = 43,
    LANGUAGE_TSX = 44,
    LANGUAGE_TYPESCRIPT = 45,
    LANGUAGE_VISUALBASIC = 46,
    LANGUAGE_VUE = 47,
    LANGUAGE_XML = 48,
    LANGUAGE_XSL = 49,
    LANGUAGE_YAML = 50,
    LANGUAGE_SVELTE = 51,
    LANGUAGE_TOML = 52,
    LANGUAGE_DART = 53,
    LANGUAGE_RST = 54,
    LANGUAGE_OCAML = 55,
    LANGUAGE_CMAKE = 56,
    LANGUAGE_PASCAL = 57,
    LANGUAGE_ELIXIR = 58,
    LANGUAGE_FSHARP = 59,
    LANGUAGE_LISP = 60,
    LANGUAGE_MATLAB = 61,
    LANGUAGE_POWERSHELL = 62,
    LANGUAGE_SOLIDITY = 63,
    LANGUAGE_ADA = 64,
    LANGUAGE_OCAML_INTERFACE = 65,
    LANGUAGE_TREE_SITTER_QUERY = 66,
    LANGUAGE_APL = 67,
    LANGUAGE_ASSEMBLY = 68,
    LANGUAGE_COBOL = 69,
    LANGUAGE_CRYSTAL = 70,
    LANGUAGE_EMACS_LISP = 71,
    LANGUAGE_ERLANG = 72,
    LANGUAGE_FORTRAN = 73,
    LANGUAGE_FREEFORM = 74,
    LANGUAGE_GRADLE = 75,
    LANGUAGE_HACK = 76,
    LANGUAGE_MAVEN = 77,
    LANGUAGE_M68KASSEMBLY = 78,
    LANGUAGE_SAS = 79,
    LANGUAGE_UNIXASSEMBLY = 80,
    LANGUAGE_VBA = 81,
    LANGUAGE_VIMSCRIPT = 82,
    LANGUAGE_WEBASSEMBLY = 83,
    LANGUAGE_BLADE = 84,
    LANGUAGE_ASTRO = 85,
    LANGUAGE_MUMPS = 86,
    LANGUAGE_GDSCRIPT = 87,
    LANGUAGE_NIM = 88,
    LANGUAGE_PROLOG = 89,
    LANGUAGE_MARKDOWN_INLINE = 90,
}

[global::ProtoBuf.ProtoContract()]
public enum StopReason
{
    STOP_REASON_UNSPECIFIED = 0,
    STOP_REASON_INCOMPLETE = 1,
    STOP_REASON_STOP_PATTERN = 2,
    STOP_REASON_MAX_TOKENS = 3,
    STOP_REASON_MIN_LOG_PROB = 4,
    STOP_REASON_MAX_NEWLINES = 5,
    STOP_REASON_EXIT_SCOPE = 6,
}

[global::ProtoBuf.ProtoContract()]
public enum FilterReason
{
    FILTER_REASON_NONE = 0,
    FILTER_REASON_INCOMPLETE = 1,
    FILTER_REASON_EMPTY = 2,
    FILTER_REASON_REPETITIVE = 3,
    FILTER_REASON_DUPLICATE = 4,
    FILTER_REASON_LONG_LINE = 5,
    FILTER_REASON_COMPLETIONS_CUTOFF = 6,
}

[global::ProtoBuf.ProtoContract()]
public enum CodeContextType
{
    CODE_CONTEXT_TYPE_UNSPECIFIED = 0,
    CODE_CONTEXT_TYPE_FUNCTION = 1,
    CODE_CONTEXT_TYPE_CLASS = 2,
    CODE_CONTEXT_TYPE_IMPORT = 3,
    CODE_CONTEXT_TYPE_NAIVE_LINECHUNK = 4,
    CODE_CONTEXT_TYPE_REFERENCE_FUNCTION = 5,
    CODE_CONTEXT_TYPE_REFERENCE_CLASS = 6,
    CODE_CONTEXT_TYPE_FILE = 7,
}

[global::ProtoBuf.ProtoContract()]
public enum CodeiumState
{
    CODEIUM_STATE_UNSPECIFIED = 0,
    CODEIUM_STATE_INACTIVE = 1,
    CODEIUM_STATE_PROCESSING = 2,
    CODEIUM_STATE_SUCCESS = 3,
    CODEIUM_STATE_WARNING = 4,
    CODEIUM_STATE_ERROR = 5,
}

[global::ProtoBuf.ProtoContract()]
public enum CompletionSource
{
    COMPLETION_SOURCE_UNSPECIFIED = 0,
    COMPLETION_SOURCE_TYPING_AS_SUGGESTED = 1,
    COMPLETION_SOURCE_CACHE = 2,
    COMPLETION_SOURCE_NETWORK = 3,
}

[global::ProtoBuf.ProtoContract()]
public enum CompletionPartType
{
    COMPLETION_PART_TYPE_UNSPECIFIED = 0,
    COMPLETION_PART_TYPE_INLINE = 1,
    COMPLETION_PART_TYPE_BLOCK = 2,
    COMPLETION_PART_TYPE_INLINE_MASK = 3,
}

[global::ProtoBuf.ProtoContract()]
public enum LineType
{
    LINE_TYPE_UNSPECIFIED = 0,
    LINE_TYPE_SINGLE = 1,
    LINE_TYPE_MULTI = 2,
}

[global::ProtoBuf.ProtoContract()]
public enum PromptElementKind
{
    PROMPT_ELEMENT_KIND_UNSPECIFIED = 0,
    PROMPT_ELEMENT_KIND_FILE_MARKER = 2,
    PROMPT_ELEMENT_KIND_OTHER_DOCUMENT = 4,
    PROMPT_ELEMENT_KIND_BEFORE_CURSOR = 5,
    PROMPT_ELEMENT_KIND_AFTER_CURSOR = 7,
    PROMPT_ELEMENT_KIND_FIM = 8,
    PROMPT_ELEMENT_KIND_SOT = 9,
    PROMPT_ELEMENT_KIND_EOT = 10,
    PROMPT_ELEMENT_KIND_CODE_CONTEXT_ITEM = 13,
    PROMPT_ELEMENT_KIND_INSTRUCTION = 14,
    PROMPT_ELEMENT_KIND_SELECTION = 15,
}

[global::ProtoBuf.ProtoContract()]
public enum ChatMessageSource
{
    CHAT_MESSAGE_SOURCE_UNSPECIFIED = 0,
    CHAT_MESSAGE_SOURCE_USER = 1,
    CHAT_MESSAGE_SOURCE_SYSTEM = 2,
    CHAT_MESSAGE_SOURCE_UNKNOWN = 3,
}

[global::ProtoBuf.ProtoContract()]
public enum UnifiedDiffLineType
{
    UNIFIED_DIFF_LINE_TYPE_UNSPECIFIED = 0,
    UNIFIED_DIFF_LINE_TYPE_INSERT = 1,
    UNIFIED_DIFF_LINE_TYPE_DELETE = 2,
    UNIFIED_DIFF_LINE_TYPE_UNCHANGED = 3,
}

[global::ProtoBuf.ProtoContract()]
public enum ContextInclusionType
{
    CONTEXT_INCLUSION_TYPE_UNSPECIFIED = 0,
    CONTEXT_INCLUSION_TYPE_INCLUDE = 1,
    CONTEXT_INCLUSION_TYPE_EXCLUDE = 2,
}

[global::ProtoBuf.ProtoContract()]
public enum ChatFeedbackType
{
    FEEDBACK_TYPE_UNSPECIFIED = 0,
    FEEDBACK_TYPE_ACCEPT = 1,
    FEEDBACK_TYPE_REJECT = 2,
    FEEDBACK_TYPE_COPIED = 3,
    FEEDBACK_TYPE_ACCEPT_DIFF = 4,
    FEEDBACK_TYPE_REJECT_DIFF = 5,
    FEEDBACK_TYPE_APPLY_DIFF = 6,
    FEEDBACK_TYPE_INSERT_AT_CURSOR = 7,
}

[global::ProtoBuf.ProtoContract()]
public enum ActiveEditorType
{
    ACTIVE_EDITOR_TYPE_UNSPECIFIED = 0,
    ACTIVE_EDITOR_TYPE_TEXT_EDITOR = 1,
    ACTIVE_EDITOR_TYPE_TERMINAL = 2,
}

[global::ProtoBuf.ProtoContract()]
public enum UserTeamStatus
{
    USER_TEAM_STATUS_UNSPECIFIED = 0,
    USER_TEAM_STATUS_PENDING = 1,
    USER_TEAM_STATUS_APPROVED = 2,
    USER_TEAM_STATUS_REJECTED = 3,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192, IDE0028
#endregion
